<?php
namespace Drupal\rest_output\Encoder;

class CsvEncoder extends \Symfony\Component\Serializer\Encoder\CsvEncoder {
  protected $format = 'csv';

  public function decode(string $data, string $format, array $context = []): mixed
  {
    $context[CsvEncoder::AS_COLLECTION_KEY] = false;
    return parent::decode($data, $format, $context); // TODO: Change the autogenerated stub
  }
}
